name: Build Package

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      
      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: 'oracle'
          java-version: '21'
          cache: 'maven'
      
      - name: Package using jlink
        run: mvn javafx:jlink

      - name: Create archive
        run: |
          mkdir -p artifacts
          zip -r artifacts/build-${{ matrix.os }}.zip ./*

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
            name: build-${{ matrix.os }}
            path: ./*

