name: Build Package

on:
  push:
    branches:
      - main

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]
            
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4
            
            - name: Set up java
              uses: actions/setup-java@v5
              with:
                distribution: 'oracle'
                java-version: '21'
                cache: 'maven'
            
            
            - name: List files
              run: ls target/image/bin

